name: c_for_chat
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.6
  cloud_firestore: ^4.4.0
  firebase_storage: ^11.0.11
  firebase_core: ^2.5.0
  image_picker: ^0.8.6+1
  image_cropper: ^1.0.1
  uuid: ^3.0.7
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: SourceSerifPro
      fonts:
        - asset: fonts/SourceSerifPro-Regular.ttf
    - family: TiltNeon
      fonts:
        - asset: fonts/TiltNeon-Regular-VariableFont_XROT,YROT.ttf

